//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TptMain.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.4.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://tpt-server.biblica.com/api")]
        public string DEFAULT_SERVER_URI {
            get {
                return ((string)(this["DEFAULT_SERVER_URI"]));
            }
            set {
                this["DEFAULT_SERVER_URI"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30000")]
        public int DEFAULT_REQUEST_TIMEOUT_IN_MS {
            get {
                return ((int)(this["DEFAULT_REQUEST_TIMEOUT_IN_MS"]));
            }
            set {
                this["DEFAULT_REQUEST_TIMEOUT_IN_MS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int PREVIEW_JOB_UPDATE_INTERVAL_IN_SEC {
            get {
                return ((int)(this["PREVIEW_JOB_UPDATE_INTERVAL_IN_SEC"]));
            }
            set {
                this["PREVIEW_JOB_UPDATE_INTERVAL_IN_SEC"] = value;
            }
        }
    }
}
